# config/config.properties
browser=chrome
baseUrl=https://www.saucedemo.com
implicitWait=10
explicitWait=15
headless=false
# screenshotOnFailure=true
cartItemsDataFile=src/test/resources/testdata/cart_items.xlsx
cartItemsSheetName=CartItems